require("globals")
require("vim_g")
require("settings")
require("mappings")
require("autocmd")
-- Install Plugins
require("packages")
-- Init Plugins
require("theme")
require("plugins/transparency")
require("plugins/hop")
require("plugins/statusline")
require("plugins/nvim-autopairs")
require("plugins/bufferline")
require("plugins/nvim-colorizer")
require("plugins/nvim-tree")
-- Auto Completions and LSP
require("plugins/rusty-tools")
require("plugins/cmp")
require("plugins/gitsigns")
require("plugins/nvim-dap-ui")
require("plugins/cargo_crates")