-- Built In Keymaps
require("keymaps/common_keys")
require("keymaps/system_clipboard")
require("keymaps/ctrl_arrowkeys")
require("keymaps/move_lines")
require("keymaps/split")
require("keymaps/buffer_manager")
require("keymaps/navigate_panes")
require("keymaps/save_file_cmd")
require("keymaps/undo_redo_cmd")
require("keymaps/resize")
require("keymaps/tab_manager")

-- Plugins
require("keymaps/undo_tree")
require("keymaps/smart_quit")
require("keymaps/nvim_tree_cmd")
require("keymaps/lsp_keymap")
require("keymaps/hop")
require("keymaps/crates")
require("keymaps/telescope")
require("keymaps/transparency")